# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Update Newsletter

on: workflow_dispatch

jobs:
  run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: ls
        cache: 'yarn'
    - run: yarn install
    - run: yarn build:scripts
    - run: yarn newsletters
      env:
        NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Update blog
        
